port: 7890
socks-port: 7891
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
# meta only
geodata-mode: true
global-client-fingerprint: chrome
tcp-concurrent: true

ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 119.28.28.28
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  
proxies:
  - name: sj
    type: vless
    server: 45.139.193.213
    port: 3443
    skip-cert-verify: true
    uuid: 8ed8efb7-457e-4f8f-a903-713fe04ad1c2
    tls: true
    udp: true
    flow: 
    servername: www.docker.com
    network: grpc
    grpc-opts:
      grpc-service-name: "sing-box"
      grpc-multi-mode: true
    reality-opts:
      public-key: daANefCDgE-0VHJLkPqHjtZ_HUTu-95Fnmk6E8rjfEU
      short-id: "5d2e3ed92cf8a73b"
    client-fingerprint: chrome
  - name: jp
    type: vless
    server: 195.245.242.126
    port: 3443
    skip-cert-verify: true
    uuid: 8ed8efb7-457e-4f8f-a903-713fe04ad1c2
    tls: true
    udp: true
    flow: 
    servername: www.docker.com
    network: grpc
    grpc-opts:
      grpc-service-name: "sing-box"
      grpc-multi-mode: true
    reality-opts:
      public-key: daANefCDgE-0VHJLkPqHjtZ_HUTu-95Fnmk6E8rjfEU
      short-id: "5d2e3ed92cf8a73b"
    client-fingerprint: chrome
  - name: jp1
    type: vless
    server: 147.78.247.80
    port: 3443
    skip-cert-verify: true
    uuid: 8ed8efb7-457e-4f8f-a903-713fe04ad1c2
    tls: true
    udp: true
    flow: 
    servername: www.docker.com
    network: grpc
    grpc-opts:
      grpc-service-name: "sing-box"
      grpc-multi-mode: true
    reality-opts:
      public-key: daANefCDgE-0VHJLkPqHjtZ_HUTu-95Fnmk6E8rjfEU
      short-id: "5d2e3ed92cf8a73b"
    client-fingerprint: chrome
  - name: hka
    type: vless
    server: 43.154.55.240
    port: 443
    skip-cert-verify: true
    uuid: 8ed8efb7-457e-4f8f-a903-713fe04ad1c2
    tls: true
    udp: true
    flow: 
    servername: www.docker.com
    network: grpc
    grpc-opts:
      grpc-service-name: "sing-box"
      grpc-multi-mode: true
    reality-opts:
      public-key: daANefCDgE-0VHJLkPqHjtZ_HUTu-95Fnmk6E8rjfEU
      short-id: "5d2e3ed92cf8a73b"
    client-fingerprint: chrome
  - name: kr
    type: vless
    server: 193.122.124.191
    port: 3443
    skip-cert-verify: true
    uuid: 8ed8efb7-457e-4f8f-a903-713fe04ad1c2
    tls: true
    udp: true
    flow: 
    servername: www.docker.com
    network: grpc
    grpc-opts:
      grpc-service-name: "sing-box"
      grpc-multi-mode: true
    reality-opts:
      public-key: daANefCDgE-0VHJLkPqHjtZ_HUTu-95Fnmk6E8rjfEU
      short-id: "5d2e3ed92cf8a73b"
    client-fingerprint: chrome
  - name: hka-trojan
    type: trojan
    server: 43.154.55.240
    port: 443
    password: 9448new
    client-fingerprint: chrome
    sni: hk-trojan.aliz.work
    alpn:
      - h2
      - http/1.1
  - name: jp1-trojan
    type: trojan
    server: 147.78.247.80
    port: 3443
    password: 9448new
    client-fingerprint: chrome
    sni: jp1-trojan.aliz.work
    alpn:
      - h2
      - http/1.1
  - name: kr-trojan
    type: trojan
    server: 193.122.124.191
    port: 3443
    password: 9448new
    client-fingerprint: chrome
    sni: kr-trojan.aliz.work
    alpn:
      - h2
      - http/1.1
  - name: jp-trojan
    type: trojan
    server: 195.245.242.126
    port: 3443
    password: 9448new
    client-fingerprint: chrome
    sni: jp-trojan.aliz.work
    alpn:
      - h2
      - http/1.1
  - name: sj-trojan
    type: trojan
    server: 45.139.193.213
    port: 3443
    password: 9448new
    client-fingerprint: chrome
    sni: sj-trojan.aliz.work
    alpn:
      - h2
      - http/1.1
  - name: kr-shadowtls
    type: ss
    server: 193.122.124.191
    port: 7443
    cipher: 2022-blake3-aes-128-gcm
    password: rObhdH4a89qzQa8oAgMycQ==
    smux:
        enabled: false
        protocol: h2mux
        max-connections: 4
        min-streams: 4
        only-tcp: false
    plugin: shadow-tls
    plugin-opts:
      host: "addons.mozilla.org"
      password: rObhdH4a89qzQa8oAgMycQ==
      version: 3
      client-fingerprint: chrome
  - name: sj-shadowtls
    type: ss
    server: 45.139.193.213
    port: 3443
    cipher: 2022-blake3-aes-128-gcm
    password: rObhdH4a89qzQa8oAgMycQ==
    smux:
        enabled: false
        protocol: h2mux
        max-connections: 4
        min-streams: 4
        only-tcp: false
    plugin: shadow-tls
    plugin-opts:
      host: "addons.mozilla.org"
      password: rObhdH4a89qzQa8oAgMycQ==
      version: 3
      client-fingerprint: chrome
  - name: jp1-shadowtls
    type: ss
    server: 147.78.247.80
    port: 3443
    cipher: 2022-blake3-aes-128-gcm
    password: rObhdH4a89qzQa8oAgMycQ==
    smux:
        enabled: false
        protocol: h2mux
        max-connections: 4
        min-streams: 4
        only-tcp: false
    plugin: shadow-tls
    plugin-opts:
      host: "addons.mozilla.org"
      password: rObhdH4a89qzQa8oAgMycQ==
      version: 3
      client-fingerprint: chrome
  - name: jp-shadowtls
    type: ss
    server: 195.245.242.126
    port: 3443
    cipher: 2022-blake3-aes-128-gcm
    password: rObhdH4a89qzQa8oAgMycQ==
    smux:
        enabled: false
        protocol: h2mux
        max-connections: 4
        min-streams: 4
        only-tcp: false
    plugin: shadow-tls
    plugin-opts:
      host: "addons.mozilla.org"
      password: rObhdH4a89qzQa8oAgMycQ==
      version: 3
      client-fingerprint: chrome
  - name: hka-shadowtls
    type: ss
    server: 43.154.55.240
    port: 443
    cipher: 2022-blake3-aes-128-gcm
    password: rObhdH4a89qzQa8oAgMycQ==
    smux:
        enabled: false
        protocol: h2mux
        max-connections: 4
        min-streams: 4
        only-tcp: false
    plugin: shadow-tls
    plugin-opts:
      host: "addons.mozilla.org"
      password: rObhdH4a89qzQa8oAgMycQ==
      version: 3
      client-fingerprint: chrome
  - name: la-shadowtls
    type: ss
    server: 198.211.24.188
    port: 443
    cipher: 2022-blake3-aes-128-gcm
    password: rObhdH4a89qzQa8oAgMycQ==
    smux:
        enabled: false
        protocol: h2mux
        max-connections: 4
        min-streams: 4
        only-tcp: false
    plugin: shadow-tls
    plugin-opts:
      host: "addons.mozilla.org"
      password: rObhdH4a89qzQa8oAgMycQ==
      version: 3
      client-fingerprint: chrome
  - name: kr-tuic
    server: kr.252798.xyz
    port: 6443
    type: tuic
    uuid: 37d59edb-6e4f-43ff-a439-ee87f0216de8
    password: foobar
    heartbeat-interval: 10000
    alpn: [h3]
    udp-relay-mode: quic
    congestion-controller: bbr
    disable-sni: true
    reduce-rtt: true
    request-timeout: 8000
    fast-open: true
  - name: jp1-tuic
    server: jp1.aliz.work
    port: 7443
    type: tuic
    uuid: 37d59edb-6e4f-43ff-a439-ee87f0216de8
    password: foobar
    heartbeat-interval: 10000
    alpn: [h3]
    udp-relay-mode: quic
    congestion-controller: bbr
    disable-sni: true
    reduce-rtt: true
    request-timeout: 8000
    fast-open: true
  - name: la-hyse
    type: hysteria2
    server: 198.211.24.188
    port: 8443
    password: "9448new"
    obfs: salamander
    obfs-password: fuckme
    protocol: udp
    sni: us-trojan.aliz.work
    up: "50 Mbps"
    down: "150 Mbps"
    alpn:
      - h3
    fast-open: true
  - name: us-hyse
    type: hysteria2
    server: 104.36.85.36
    port: 8442
    password: "9448new"
    obfs: salamander
    obfs-password: fuckme
    protocol: udp
    sni: us-trojan.aliz.work
    up: "50 Mbps"
    down: "150 Mbps"
    alpn:
      - h3
    fast-open: true
  - name: la5-hyse
    type: hysteria2
    server: 141.11.92.27
    port: 8440
    password: "9448new"
    obfs: salamander
    obfs-password: fuckme
    protocol: udp
    sni: sj818.252798.xyz
    up: "50 Mbps"
    down: "150 Mbps"
    alpn:
      - h3
    fast-open: true
         
proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - hka
      - kr
      - sj
      - jp
      - jp1
      - hka-trojan
      - jp1-trojan
      - kr-trojan
      - jp-trojan
      - sj-trojan
      - kr-shadowtls
      - hka-shadowtls
      - jp1-shadowtls
      - la-shadowtls
      - jp-shadowtls
      - sj-shadowtls
      - kr-tuic
      - jp1-tuic
      - la5-hyse
      - la-hyse
      - us-hyse
      
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
  - RULE-SET,reject,REJECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,applications,DIRECT
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,facebook,PROXY
  - GEOSITE,youtube,PROXY
  - GEOSITE,gfw,PROXY
  - GEOSITE,greatfire,PROXY
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,telegram,PROXY,no-resolve
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,PROXY
