port: 7890
socks-port: 7891
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
# meta only
geodata-mode: true
global-client-fingerprint: chrome
tcp-concurrent: true

ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 119.28.28.28
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  
proxies:
  - name: sj
    type: vless
    server: sj.252798.xyz
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "sj.252798.xyz"
  - name: jp
    type: vless
    server: jp.252798.xyz
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "jp.252798.xyz"
  - name: sj1
    type: vless
    server: sj.alichen.top
    port: 1443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "sj.alichen.top"
  - name: jp1
    type: vless
    server: jp.alichen.top
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "jp.alichen.top"
  - name: hka
    type: vless
    server: hka.252798.xyz
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "hka.252798.xyz"
  - name: kr
    type: vless
    server: kr.252798.xyz
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "kr.252798.xyz"
  - name: la
    type: vless
    server: la.alichen.top
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "la.alichen.top"
      grpc-multi-mode: true
  - name: la-hyse
    type: hysteria
    server: la.alichen.top
    port: 5666
    auth_str: "9448new"
    protocol: wechat-video
    up: "30 Mbps"
    down: "200 Mbps"
    alpn:
      - h3
    fast-open: true
  - name: sj-hyse
    type: hysteria
    server: sj.alichen.top
    port: 5566
    auth_str: "9448new"
    protocol: wechat-video
    up: "30 Mbps"
    down: "200 Mbps"
    alpn:
      - h3
    fast-open: true
  - name: sj-tic
    type: tuic
    server: sj.alichen.top
    port: 3443
    token: "9448new"
    fast-open: true
    alpn:
      - h3
    udp-relay-mode: native
    reduce-rtt: true
    congestion-controller: bbr
  - name: jp1-vision
    type: vless
    server: jp.alichen.top
    port: 2443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    udp: true
    network: tcp
    flow: xtls-rprx-vision
    reality-opts:
      public-key: IrFtV1hpCd7EZGxlJKMMrhMe8gjzFgwnrsmu2_tTPDg
      short-id: "bb1212"
    client-fingerprint: chrome
  - name: jp-vision
    type: vless
    server: jp.252798.xyz
    port: 2443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    udp: true
    network: grpc
    flow: 
    grpc-opts:
      grpc-service-name: "vision"
      grpc-multi-mode: true
    reality-opts:
      public-key: IrFtV1hpCd7EZGxlJKMMrhMe8gjzFgwnrsmu2_tTPDg
      short-id: "bb1212"
    client-fingerprint: chrome
  - name: kr-vision
    type: vless
    server: kr.252798.xyz
    port: 2443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    udp: true
    network: tcp
    flow: xtls-rprx-vision
    client-fingerprint: chrome
  - name: sj-vision
    type: vless
    server: sj.252798.xyz
    port: 2443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    udp: true
    network: tcp
    flow: xtls-rprx-vision
    reality-opts:
      public-key: IrFtV1hpCd7EZGxlJKMMrhMe8gjzFgwnrsmu2_tTPDg
      short-id: "bb1212"
    client-fingerprint: chrome
  - name: sj1-vision
    type: vless
    server: sj.alichen.top
    port: 2443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    udp: true
    network: tcp
    flow: xtls-rprx-vision
    reality-opts:
      public-key: IrFtV1hpCd7EZGxlJKMMrhMe8gjzFgwnrsmu2_tTPDg
      short-id: "bb1212"
    client-fingerprint: chrome
  - name: hka-vision
    type: vless
    server: 43.154.55.240
    port: 1443
    skip-cert-verify: true
    uuid: 8ed8efb7-457e-4f8f-a903-713fe04ad1c2
    tls: true
    udp: true
    flow: 
    servername: www.docker.com
    network: grpc
    grpc-opts:
      grpc-service-name: "sing-box"
      grpc-multi-mode: true
    reality-opts:
      public-key: daANefCDgE-0VHJLkPqHjtZ_HUTu-95Fnmk6E8rjfEU
      short-id: "5d2e3ed92cf8a73b"
    client-fingerprint: chrome
  - name: kr-shadowtls
    type: ss
    server: 193.122.124.191
    port: 7443
    cipher: 2022-blake3-aes-128-gcm
    password: rObhdH4a89qzQa8oAgMycQ==
    plugin: shadow-tls
    plugin-opts:
        host: "addons.mozilla.org"
        password: rObhdH4a89qzQa8oAgMycQ==
        version: 3
        client-fingerprint: chrome
  - name: sj1-shadowtls
    type: ss
    server: 171.22.130.57
    port: 4443
    cipher: 2022-blake3-aes-128-gcm
    password: rObhdH4a89qzQa8oAgMycQ==
    plugin: shadow-tls
    plugin-opts:
        host: "addons.mozilla.org"
        password: rObhdH4a89qzQa8oAgMycQ==
        version: 3
        client-fingerprint: chrome
        
proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - hka
      - kr
      - sj
      - jp
      - jp1
      - la
      - sj-tic
      - la-hyse
      - sj-hyse
      - jp1-vision
      - jp-vision
      - kr-vision
      - sj-vision
      - sj1-vision
      - hka-vision
      - kr-shadowtls
      - sj1-shadowtls
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
  - RULE-SET,reject,REJECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,applications,DIRECT
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,facebook,PROXY
  - GEOSITE,youtube,PROXY
  - GEOSITE,gfw,PROXY
  - GEOSITE,greatfire,PROXY
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,telegram,PROXY,no-resolve
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,PROXY
