port: 7890
socks-port: 7891
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
# meta only
geodata-mode: true
global-client-fingerprint: chrome
tcp-concurrent: true

ipv6: false
external-controller: 127.0.0.1:9090
interface-name: en0
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 119.28.28.28
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  
proxies:
  - name: sj
    type: vless
    server: sj.252798.xyz
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "sj.252798.xyz"
  - name: jp
    type: vless
    server: jp.252798.xyz
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "jp.252798.xyz"
  - name: sj1
    type: vless
    server: sj.alichen.top
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "sj.alichen.top"
  - name: jp1
    type: vless
    server: jp.alichen.top
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "jp.alichen.top"
  - name: hka
    type: vless
    server: hka.252798.xyz
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "hka.252798.xyz"
  - name: kr
    type: vless
    server: kr.252798.xyz
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "kr.252798.xyz"
  - name: la
    type: vless
    server: la.alichen.top
    port: 443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: grpc
    grpc-opts:
      grpc-service-name: "la.alichen.top"
      grpc-multi-mode: true
  - name: la-hyse
    type: hysteria
    server: la.alichen.top
    port: 5666
    auth_str: "9448new"
    protocol: wechat-video
    up: "30 Mbps"
    down: "200 Mbps"
    alpn:
      - h3
    fast-open: true
  - name: sj-hyse
    type: hysteria
    server: sj.alichen.top
    port: 5566
    auth_str: "9448new"
    protocol: wechat-video
    up: "30 Mbps"
    down: "200 Mbps"
    alpn:
      - h3
    fast-open: true
  - name: sj-tic
    type: tuic
    server: sj.alichen.top
    port: 3443
    token: "9448new"
    fast-open: true
    alpn:
      - h3
    udp-relay-mode: native
    reduce-rtt: true
    congestion-controller: bbr
  - name: jp1-vision
    type: vless
    server: jp.alichen.top
    port: 2443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: tcp
    flow: xtls-rprx-vision
    client-fingerprint: chrome
  - name: jp-vision
    type: vless
    server: jp.252798.xyz
    port: 2443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: tcp
    flow: xtls-rprx-vision
    client-fingerprint: chrome
  - name: kr-vision
    type: vless
    server: kr.252798.xyz
    port: 2443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: tcp
    flow: xtls-rprx-vision
    client-fingerprint: chrome
  - name: sj-vision
    type: vless
    server: sj.252798.xyz
    port: 2443
    skip-cert-verify: true
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    tls: true
    network: tcp
    flow: xtls-rprx-vision
    client-fingerprint: chrome
  - name: jp1-reality
    type: vless
    server: jp.alichen.top
    port: 4443
    uuid: 6373c273-4a52-4e5d-9ee9-afd23107bdc3
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: jp.alichen.top
    reality-opts:
      public-key: IrFtV1hpCd7EZGxlJKMMrhMe8gjzFgwnrsmu2_tTPDg
      short-id: 1212
    client-fingerprint: chrome
  
proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - hka
      - kr
      - sj
      - sj1
      - jp
      - jp1
      - la
      - sj-tic
      - la-hyse
      - sj-hyse
      - jp1-vision
      - jp-vision
      - kr-vision
      - sj-vision
      - jp1-reality

rules:
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,facebook,PROXY
  - GEOSITE,youtube,PROXY
  - GEOSITE,gfw,PROXY
  - GEOSITE,greatfire,PROXY
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,telegram,PROXY,no-resolve
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,PROXY
